### PR TITLE
defaults is 13?

### PR DESCRIPTION
**Pull request by yutayu**
is it certain?

### CODE REVIEW

**Comment by yutayu** [comment]
usually, last leaf qdisc number is default.

**Comment by tohojo** [comment]
yutayu <notifications@github.com> writes:

> usually, last leaf qdisc number is default.

I'm not sure what you are asking, exactly?

**Comment by yutayu** [comment]
> yutayu <notifications@github.com> writes:
> usually, last leaf qdisc number is default.
> I'm not sure what you are asking, exactly?

13 is last , largest.
then 13 is default , in this case.

**Comment by yutayu** [comment]
I thought that a default qdisc catches bulk packets.
but, now this scripts set 12 as default ,This is second qdisc , not last.

**Comment by moeller0** [comment]
Well, we do have the following rule:
  # Need a catchall rule

    $TC filter add dev $IFACE parent 1:0 protocol all prio 999 u32 \
        match ip protocol 0 0x00 flowid 1:12

So I believe we are fine, as is, no?

On March 9, 2019 12:35:39 PM GMT+01:00, yutayu <notifications@github.com> wrote:
>I thought that a default qdisc catches bulk packets.
>but, now this scripts set 12 as default ,This is second qdisc , not
>last.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/tohojo/sqm-scripts/pull/86#issuecomment-471169589

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by yutayu** [comment]
On Sat, 09 Mar 2019 04:14:50 -0800
moeller0 <notifications@github.com> wrote:

> Well, we do have the following rule:
>   # Need a catchall rule
> 
>     $TC filter add dev $IFACE parent 1:0 protocol all prio 999 u32 \
>         match ip protocol 0 0x00 flowid 1:12
> 
> So I believe we are fine, as is, no?
> 

I saw it now on sqm-scipt.
I think default should be largest number.
In this cake 1:13.
Then , default is 13 and last prio.

**Comment by yutayu** [comment]
ignored XD
I mean we need no class for bulk packets. 
To set default for bulk packets is all.

**Pull request closed without merging**
