### PR TITLE
Burst by duration squashed

### PR DESCRIPTION
**Pull request by moeller0**
So here is an attempt to tidy up the burst_by_duration PR, by offering a slightly less messy version with fewer commits.
@tohojo please let me know whether that helps at all, or whether you would prefer the original PR?

### CODE REVIEW

**Comment by tohojo** [comment]
Yeah, this is much better, thanks!

**Comment by moeller0** [comment]
> Yeah, this is much better, thanks!

Good, should we now close the other PR and redirect any further discussion here, or should we only do this when/if we merge this?

**Comment by tohojo** [comment]
moeller0 <notifications@github.com> writes:

>> Yeah, this is much better, thanks!
>
> Good, should we now close the other PR and redirect any further
> discussion here, or should we only do this when/if we merge this?

Yeah, no reason to have duplicates

**Comment by moeller0** [comment]
Okay, the old PR is closed now.

**Comment by yutayu** [comment]
It stops download from google drive with this branch , again :(

**Comment by moeller0** [comment]
> It stops download from google drive with this branch , again :(
File downloading is large size.

Mmmh, what is the output of: 
tc -d qdisc
tc -d qdisc
dmesg
logread # (but only include say the last 30 lines or so)

when the download runs ad when it stops? Make sure to redact the logread output to remove any sensitive information, same for dmesg.
Are you sure that you never see this issue with the current sqm-scripts master branch?

**Comment by moeller0** [comment]
The next thing to try, will be to make sure that 
class htb 1:11 parent 1:1 leaf 110: prio rate 128Kbit ceil 271Kbit burst 1600b cburst 1599b

also gets the same burst as the others. (Which should not be an issue, but should is way to week)

**Comment by yutayu** [comment]
tc -d qdisc
qdisc noqueue 0: dev lo root refcnt 2 
qdisc htb 1: dev eth0 root refcnt 2 r2q 10 default 18 direct_packets_stat 6 ver 3.17 direct_qlen 3
 linklayer atm overhead -4 mtu 2047 tsize 512 
qdisc fq_codel 120: dev eth0 parent 1:12 limit 1001p flows 1024 quantum 300 target 17.2ms interval 112.2ms memory_limit 32Mb 
qdisc fq_codel 130: dev eth0 parent 1:13 limit 1001p flows 1024 quantum 300 target 17.2ms interval 112.2ms memory_limit 32Mb 
qdisc fq_codel 110: dev eth0 parent 1:11 limit 1001p flows 1024 quantum 300 target 17.2ms interval 112.2ms memory_limit 32Mb 
qdisc ingress ffff: dev eth0 parent ffff:fff1 ---------------- 
qdisc htb 1: dev ifb4eth0 root refcnt 2 r2q 10 default 16 direct_packets_stat 0 ver 3.17 direct_qlen 32
 linklayer atm overhead -4 mtu 2047 tsize 512 
qdisc fq_codel 110: dev ifb4eth0 parent 1:10 limit 1001p flows 1024 quantum 300 target 5.0ms interval 100.0ms memory_limit 32Mb ecn 

Last Downloading was over.
I will have a next chance by tomorrow.

( I start to think dnsmasq problem , hold on )

**Comment by moeller0** [comment]
> Last Downloading was over.
I will have a next chance by tomorrow.

> ( I start to think dnsmasq problem , hold on )

Please keep me informed.

**Comment by moeller0** [comment]
Mmmh, if you assume this branch not to be the culprit, how about you try with the master branch tomorrow, if that fails as well it might still indicate sqm, but not these few changes.
I am not saying these changes are innocent, just that I have no good hypothesis how these could affect downloads....

**Comment by yutayu** [comment]
I comment out this line from dnsmasq.conf
#dns-forward-max=2

It seems well done : ) very sorry.

**Comment by yutayu** [comment]
> On Oct 30, 2018, at 15:10, yutayu ***@***.***> wrote: I comment out this line from dnsmasq.conf #dns-forward-max=2 It seems well done : ) very sorry.
> So can you artificially recreate the issue by toggling between: #dns-forward-max=2 and dns-forward-max=2 even with sqm-script's master branch?
> […](#)
> — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

Sorry ,again. issue again.
Downloading from google drive with chromium stops.

journalctl -xe
-- Unit systemd-hostnamed.service has begun starting up.
Oct 30 23:24:48 raspberrypi dbus[345]: [system] Successfully activated service 'org.freedesktop.hostname1'
Oct 30 23:24:48 raspberrypi systemd[1]: Started Hostname Service.
-- Subject: Unit systemd-hostnamed.service has finished start-up
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- Unit systemd-hostnamed.service has finished starting up.
-- 
-- The start-up result is done.
Oct 30 23:25:26 raspberrypi dbus[345]: [system] Activating via systemd: service name='org.freedesktop.hostname1' unit='dbus-o
Oct 30 23:25:26 raspberrypi systemd[1]: Starting Hostname Service...
-- Subject: Unit systemd-hostnamed.service has begun start-up
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- Unit systemd-hostnamed.service has begun starting up.
Oct 30 23:25:27 raspberrypi dbus[345]: [system] Successfully activated service 'org.freedesktop.hostname1'
Oct 30 23:25:27 raspberrypi systemd[1]: Started Hostname Service.
-- Subject: Unit systemd-hostnamed.service has finished start-up
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- Unit systemd-hostnamed.service has finished starting up.
-- 
-- The start-up result is done.
Oct 30 23:25:59 raspberrypi dbus[345]: [system] Activating via systemd: service name='org.freedesktop.hostname1' unit='dbus-o
Oct 30 23:25:59 raspberrypi systemd[1]: Starting Hostname Service...
-- Subject: Unit systemd-hostnamed.service has begun start-up
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- Unit systemd-hostnamed.service has begun starting up.
Oct 30 23:25:59 raspberrypi dbus[345]: [system] Successfully activated service 'org.freedesktop.hostname1'
Oct 30 23:25:59 raspberrypi systemd[1]: Started Hostname Service.
-- Subject: Unit systemd-hostnamed.service has finished start-up
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- Unit systemd-hostnamed.service has finished starting up.
-- 
-- The start-up result is done.
Oct 30 23:36:42 raspberrypi sudo[11147]:       pi : TTY=pts/2 ; PWD=/home/pi/sqm-scripts ; USER=root ; COMMAND=/usr/bin/make 
Oct 30 23:36:42 raspberrypi sudo[11147]: pam_unix(sudo:session): session opened for user root by (uid=0)
Oct 30 23:36:43 raspberrypi sudo[11147]: pam_unix(sudo:session): session closed for user root
Oct 30 23:36:51 raspberrypi sudo[11177]:       pi : TTY=pts/2 ; PWD=/home/pi/sqm-scripts ; USER=root ; COMMAND=/usr/bin/sqm r
Oct 30 23:36:51 raspberrypi sudo[11177]: pam_unix(sudo:session): session opened for user root by (uid=0)
Oct 30 23:36:53 raspberrypi sudo[11177]: pam_unix(sudo:session): session closed for user root

 tc -d -s qdisc
qdisc noqueue 0: dev lo root refcnt 2 
 Sent 0 bytes 0 pkt (dropped 0, overlimits 0 requeues 0) 
 backlog 0b 0p requeues 0
qdisc htb 1: dev eth0 root refcnt 2 r2q 10 default 18 direct_packets_stat 5 ver 3.17 direct_qlen 3
 linklayer atm overhead -4 mtu 2047 tsize 512 
 Sent 17531764 bytes 93593 pkt (dropped 1528, overlimits 159782 requeues 0) 
 backlog 0b 0p requeues 0
qdisc fq_codel 120: dev eth0 parent 1:12 limit 1001p flows 1024 quantum 300 target 17.2ms interval 112.2ms memory_limit 32Mb 
 Sent 17521482 bytes 93566 pkt (dropped 1527, overlimits 0 requeues 0) 
 backlog 0b 0p requeues 0
  maxpacket 1590 drop_overlimit 0 new_flow_count 20999 ecn_mark 0
  new_flows_len 0 old_flows_len 2
qdisc fq_codel 130: dev eth0 parent 1:13 limit 1001p flows 1024 quantum 300 target 17.2ms interval 112.2ms memory_limit 32Mb 
 Sent 0 bytes 0 pkt (dropped 0, overlimits 0 requeues 0) 
 backlog 0b 0p requeues 0
  maxpacket 0 drop_overlimit 0 new_flow_count 0 ecn_mark 0
  new_flows_len 0 old_flows_len 0
qdisc fq_codel 110: dev eth0 parent 1:11 limit 1001p flows 1024 quantum 300 target 17.2ms interval 112.2ms memory_limit 32Mb 
 Sent 1060 bytes 10 pkt (dropped 0, overlimits 0 requeues 0) 
 backlog 0b 0p requeues 0
  maxpacket 106 drop_overlimit 0 new_flow_count 10 ecn_mark 0
  new_flows_len 1 old_flows_len 0
qdisc ingress ffff: dev eth0 parent ffff:fff1 ---------------- 
 Sent 180982039 bytes 134239 pkt (dropped 0, overlimits 0 requeues 0) 
 backlog 0b 0p requeues 0
qdisc htb 1: dev ifb4eth0 root refcnt 2 r2q 10 default 16 direct_packets_stat 0 ver 3.17 direct_qlen 32
 linklayer atm overhead -4 mtu 2047 tsize 512 
 Sent 202029746 bytes 134238 pkt (dropped 0, overlimits 40923 requeues 0) 
 backlog 0b 0p requeues 0
qdisc fq_codel 110: dev ifb4eth0 parent 1:10 limit 1001p flows 1024 quantum 300 target 5.0ms interval 100.0ms memory_limit 32Mb ecn 
 Sent 202031336 bytes 134239 pkt (dropped 0, overlimits 0 requeues 0) 
 backlog 0b 1p requeues 0
  maxpacket 1643 drop_overlimit 0 new_flow_count 37097 ecn_mark 0 memory_used 3072
  new_flows_len 1 old_flows_len 1

but I give up. 
It seems no sign of erros.

**Comment by moeller0** [comment]
Please also add the output of 
tc -s qdisc

**Comment by yutayu** [comment]
> tc -s qdisc

qdisc noqueue 0: dev lo root refcnt 2 
 Sent 0 bytes 0 pkt (dropped 0, overlimits 0 requeues 0) 
 backlog 0b 0p requeues 0
qdisc htb 1: dev eth0 root refcnt 2 r2q 10 default 18 direct_packets_stat 5 direct_qlen 3
 Sent 63933794 bytes 358572 pkt (dropped 3663, overlimits 527532 requeues 0) 
 backlog 0b 0p requeues 0
qdisc fq_codel 120: dev eth0 parent 1:12 limit 1001p flows 1024 quantum 300 target 17.2ms interval 112.2ms memory_limit 32Mb 
 Sent 63921127 bytes 358527 pkt (dropped 3662, overlimits 0 requeues 0) 
 backlog 0b 0p requeues 0
  maxpacket 1590 drop_overlimit 0 new_flow_count 88024 ecn_mark 0
  new_flows_len 0 old_flows_len 1
qdisc fq_codel 130: dev eth0 parent 1:13 limit 1001p flows 1024 quantum 300 target 17.2ms interval 112.2ms memory_limit 32Mb 
 Sent 0 bytes 0 pkt (dropped 0, overlimits 0 requeues 0) 
 backlog 0b 0p requeues 0
  maxpacket 0 drop_overlimit 0 new_flow_count 0 ecn_mark 0
  new_flows_len 0 old_flows_len 0
qdisc fq_codel 110: dev eth0 parent 1:11 limit 1001p flows 1024 quantum 300 target 17.2ms interval 112.2ms memory_limit 32Mb 
 Sent 3445 bytes 28 pkt (dropped 0, overlimits 0 requeues 0) 
 backlog 0b 0p requeues 0
  maxpacket 583 drop_overlimit 0 new_flow_count 28 ecn_mark 0
  new_flows_len 1 old_flows_len 15
qdisc ingress ffff: dev eth0 parent ffff:fff1 ---------------- 
 Sent 684947074 bytes 504941 pkt (dropped 0, overlimits 0 requeues 0) 
 backlog 0b 0p requeues 0
qdisc htb 1: dev ifb4eth0 root refcnt 2 r2q 10 default 16 direct_packets_stat 0 direct_qlen 32
 Sent 764213360 bytes 504920 pkt (dropped 21, overlimits 185303 requeues 0) 
 backlog 0b 0p requeues 0
qdisc fq_codel 110: dev ifb4eth0 parent 1:10 limit 1001p flows 1024 quantum 300 target 5.0ms interval 100.0ms memory_limit 32Mb ecn 
 Sent 764213360 bytes 504920 pkt (dropped 21, overlimits 0 requeues 0) 
 backlog 0b 0p requeues 0
  maxpacket 1643 drop_overlimit 0 new_flow_count 143125 ecn_mark 0
  new_flows_len 0 old_flows_len 1

**Comment by yutayu** [comment]
> On Oct 30, 2018, at 15:10, yutayu ***@***.***> wrote: I comment out this line from dnsmasq.conf #dns-forward-max=2 It seems well done : ) very sorry.
> So can you artificially recreate the issue by toggling between: #dns-forward-max=2 and dns-forward-max=2 even with sqm-script's master branch?
> […](#)
> — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

I commentout it with master , now.
It doesn't stop downloading.

**Comment by moeller0** [comment]
Okay, thanks for all that testing.

What do "tc -d class show dev ifb4eth0"  and  "tc -d class show dev eth0" return on master and on burst_by_duration_squashed?

**Comment by yutayu** [comment]
> Okay, thanks for all that testing.
> 
> What do "tc -d class show dev ifb4eth0" and "tc -d class show dev eth0" return on master and on burst_by_duration_squashed?

class htb 1:11 parent 1:1 leaf 110: prio quantum rate 128Kbit ceil 271Kbit linklayer ethernet burst 1600b/1 mpu 0b cburst 1599b/1 mpu 0b level 0 
class htb 1:1 root rate 815Kbit ceil 815Kbit linklayer ethernet burst 1599b/1 mpu 0b cburst 1599b/1 mpu 0b level 7 
class htb 1:13 parent 1:1 leaf 130: prio quantum rate 135Kbit ceil 799Kbit linklayer ethernet burst 1599b/1 mpu 0b cburst 1599b/1 mpu 0b level 0 
class htb 1:12 parent 1:1 leaf 120: prio quantum rate 135Kbit ceil 799Kbit linklayer ethernet burst 1599b/1 mpu 0b cburst

class htb 1:10 parent 1:1 leaf 110: prio quantum rate 11603Kbit ceil 11603Kbit linklayer ethernet burst 1598b/1 mpu 0b cburst 1598b/1 mpu 0b level 0 
class htb 1:1 root rate 11603Kbit ceil 11603Kbit linklayer ethernet burst 1598b/1 mpu 0b cburst 1598b/1 mpu 0b level 7 

master

**Comment by yutayu** [comment]
> Okay, thanks for all that testing.
> 
> What do "tc -d class show dev ifb4eth0" and "tc -d class show dev eth0" return on master and on burst_by_duration_squashed?

class htb 1:11 parent 1:1 leaf 110: prio quantum rate 128Kbit ceil 271Kbit linklayer ethernet burst 1600b/1 mpu 0b cburst 1599b/1 mpu 0b level 0 
class htb 1:1 root rate 815Kbit ceil 815Kbit linklayer ethernet burst 1599b/1 mpu 0b cburst 1599b/1 mpu 0b level 7 
class htb 1:13 parent 1:1 leaf 130: prio quantum rate 135Kbit ceil 799Kbit linklayer ethernet burst 1599b/1 mpu 0b cburst 1599b/1 mpu 0b level 0 
class htb 1:12 parent 1:1 leaf 120: prio quantum rate 135Kbit ceil 799Kbit linklayer ethernet burst 1599b/1 mpu 0b cburst 1599b/1 mpu 0b level 0 

class htb 1:10 parent 1:1 leaf 110: prio quantum rate 11603Kbit ceil 11603Kbit linklayer ethernet burst 1598b/1 mpu 0b cburst 1598b/1 mpu 0b level 0 
class htb 1:1 root rate 11603Kbit ceil 11603Kbit linklayer ethernet burst 1598b/1 mpu 0b cburst 1598b/1 mpu 0b level 7 

burst_by_duration_squashed

**Comment by moeller0** [comment]
The two outputs look too similar to me, are you certain that the second truly is from burst_by_duration_squashed?

**Comment by yutayu** [comment]
> The two outputs look too similar to me, are you certain that the second truly is from burst_by_duration_squashed?
class htb 1:11 parent 1:1 leaf 110: prio quantum rate 128Kbit ceil 271Kbit linklayer ethernet burst 1600b/1 mpu 0b cburst 1599b/1 mpu 0b level 0 
class htb 1:1 root rate 815Kbit ceil 815Kbit linklayer ethernet burst 1748b/1 mpu 0b cburst 1748b/1 mpu 0b level 7 
class htb 1:13 parent 1:1 leaf 130: prio quantum rate 135Kbit ceil 799Kbit linklayer ethernet burst 1748b/1 mpu 0b cburst 1748b/1 mpu 0b level 0 
class htb 1:12 parent 1:1 leaf 120: prio quantum rate 135Kbit ceil 799Kbit linklayer ethernet burst 1748b/1 mpu 0b cburst 1748b/1 mpu 0b level 0 

class htb 1:10 parent 1:1 leaf 110: prio quantum rate 11603Kbit ceil 11603Kbit linklayer ethernet burst 1746b/1 mpu 0b cburst 1746b/1 mpu 0b level 0 
class htb 1:1 root rate 11603Kbit ceil 11603Kbit linklayer ethernet burst 1746b/1 mpu 0b cburst 1746b/1 mpu 0b level 7 

sorry 
burst_by_duration_squashed

**Comment by yutayu** [comment]
now ,stop even if master :(
Maybe my situation problem.
sorry.

**Comment by yutayu** [comment]
now ,stop even if master :(
Maybe my situation problem.
sorry.

**Comment by negan07** [comment]
so the cburst has increased also with <60mbps rates

**Comment by moeller0** [comment]
@yutayu 
Let's try to summarize the results so far (please correct me where I am wrong):
```
branch:        observed stalls:
nosqm         no?
master         yes
bbds            yes

bbds: burst_by_duration_squashed
nosqm: running with sqm disabled (on openwrt: /etc/init.d/sqm stop)
```
To me this looks like the issue is potentially caused by sqm-scrips, but does not seem to be caused by the code this PR introduces. Do you agree with that assessment?

**Comment by yutayu** [comment]
> @yutayu
> Let's try to summarize the results so far (please correct me where I am wrong):
> 
> ```
> branch:        observed stalls:
> nosqm         no?
> master         yes
> bbds            yes
> 
> bbds: burst_by_duration_squashed
> nosqm: running with sqm disabled (on openwrt: /etc/init.d/sqm stop)
> ```
> To me this looks like the issue is potentially caused by sqm-scrips, but does not seem to be caused by the code this PR introduces. Do you agree with that assessment?

Maybe , sorry .
Depend on downloading Time.

**Comment by negan07** [comment]
> Because downloading stops while another shaping script running.

overlaps are not recommended there could be incompatibilities each other

**Comment by yutayu** [comment]
I  am sorry to let you confuse.

**Comment by yutayu** [comment]
@moeller0 
: )
I got triple A at dslreports :P

**Comment by moeller0** [comment]
> there is another qos-sqm branch version named 2.0.0-18

Not sure what you mean, at least in this repository there does not seem to be such a branch.
[https://github.com/guidosarducci/papal-repo](url) seems to be what you are referring.
I am probably the wrong person to comment upon this, but it seems the Tony decided to give his reworked sqm "fork" more exposure and testing; which I believe is good. I am not sure what this means for PR #58 [()](url
https://github.com/tohojo/sqm-scripts/pull/58). This is a bit sad, as that PR contains a number of actual bug-fixes as well as code restructures that arguably improve sqm. I also note that sqm-scripts_2.0.0-18-git-347f803_all.ipk does not yet? include the most recent fixes changes in this repository here.

> had a look: there are some kind of modifications about llam & overhead

I had a look as well, and I have the feeling that this is even more complicated than the grown solution we have right now. 
Also, as expected for a big re-work some edge-cases seem to be handled sub-optimally (in all fairness due to all the new structure I might simply mis-interpreting the new code). For example it seems to assume that PTM framing omits the FCS and hence does not require a MPU=64 setting.

> why not taking the occasion to merge them all ?

As far as I remember, @tohojo requested some restructuring of the PR for better review (and potential/likely? merging).

IMHO, getting his fork tested externally is great; but packaging it as a higher version number but keeping the old name is unfortunate, as it will making A/B testing more difficult (as the packages can not be installed in parallel). Also it will make my hobby, supporting sqm users on the openwrt forum, harder, since I will stick to the main repository version.

**Comment by negan07** [comment]
Called branch as fork in reference of: https://github.com/tohojo/sqm-scripts/pull/58 as the conclusion of this pull req is still unknown.

My suggestion of merging was especially referred at least to the fusion of simple, simplest, simplest.tbf into one single tree with related dscp & shaper settings

the newest modifications made by guidosarducci about overhead, llam and those made here of quantum & burst could survive together with the related adjustements

Note1: didn't see any git trac about this 2.0.0-18 fork version, just found as ipk
Note2: there is also a good enhancement of cerowrt `speedtest.sh` including cpu load stats output merging  concurrent and sequential original scripts together; as in Note1 didn't found any git repository yet.

**Comment by moeller0** [comment]
Hi Negan,


> On Nov 7, 2018, at 13:03, negan07 <notifications@github.com> wrote:
> 
> Called branch as fork in reference of: #58 as the conclusion of this pull req is still unknown.

As I said, there was a request for a bit of squashing and reorganization earlier this year, review was supposed to happen after that. Not sure what Tony's plan is in regards to the PR; until I hear more I simply assume he wants broader testing.

> 
> My suggestion of merging was especially referred at least to the fusion of simple, simplest, simplest.tbf into one single tree with related dscp & shaper settings

	This merging has not received any meaningful review so far. IMHO this is a major change of what sqm-script is supposed to be that should be discussed in detail before merging. The way I see it at this really just moved the perceived complexity from the scripts into "qdisc_funcs.sh" and especially tier_shaper_htb() is everything but a generic function to create an arbitrary number of tiers HTB tree...
"    sqm_error "Unhandled args \"$dir $num_tiers $tier\" to $func in tier_shaper_$SHAPER()." basically tells it all.

> 
> the newest modifications made by guidosarducci about overhead, llam and those made here of quantum & burst could survive together with the related adjustements

	Again, these have not been reviewed by anybody and even cursory looking over revealed errors, so I believe these major restructuring changes should be given at least as much scrutiny as the rather modest changes the burst by duration branch introduced. (And I would not complain if Tony would justify each change by the "scientific" analysis he proposed for the bust by duration changes).

> 
> Note1: didn't see any git trac about this 2.0.0-18 fork version, just found as ipk

	I believe https://github.com/guidosarducci/sqm-scripts should have the sources you are looking for.

> Note2: there is also a good enhancement of cerowrt speedtest.sh including cpu load stats output merging concurrent and sequential original scripts together; as in Note1 didn't found any git repository yet.

	Well, the biggest enhancement, CPU load reporting does not work as intended yet in light of frequency scaling CPU cores, so I would rather recommend to wait a bit before using those in production; it is a good time for anybody that is not me* in helping testing and improvements of these scripts. 




*) Tony and I seem to to be too impressed by each other's level of attention to detail, so at least it is mutual.

**Comment by negan07** [comment]
I think best way should be to avoid personal issues concentrating to code issues, if any:

@guidosarducci has made many improvements in code reorganization and the shouldn't be ignored at all

you did many improvements and they can be compatible with them as the package I created more than 1 year ago for **D7000** device merges all of these forks/master/wip/branches

tested all the pull _[wip ...]_ for one years (and now also with the last changes) by all the **D7000** users without mentioning specific troubles referable to this changes:
the device is not openwrt based and people can't report over that community about an unsupported device

moreover, the modifications made by `qdisc_funcs.sh`don't involve code core modifications 

all this seems to be a justification only to avoid/skip his changes

In the opposite:

1. changing var settings just to break old configuration compatibility, even if this could be avoided;
2. skipping to push commits on forks uploading newer package binaries only;
3. bumping version packages freely without renaming;

is not the best kind of cooperation to make the tools more powerful and reliable...

**Comment by tohojo** [comment]
> all this seems to be a justification only to avoid/skip his changes

No, the pull request was put on hold because Tony wanted to clean it up
a bit before review; I guess he got sidetracked, since that never
happened. If nothing more happens I'm thinking I'll start going through
it and gradually pulling in parts of it into master.

I have nothing a priori against the changes, and there is definitely
good stuff in there; the UI changes in particular are nice. But it does
need to be reviewed properly, which is made more difficult by the wide
scope of the pull request...

**Pull request merged**
