### PR TITLE
[RFC]: Logging changes

### PR DESCRIPTION
**Pull request by moeller0**
I believe we can improve our logging game, and to get this going, here is a first propsal for the direction this should be going, IMHO. If this seems like a good idea we can see how to get rid of the legacy logging, which I believe to be much less useful than the proposed independent logging for run.sh, start-sqm and stop-sqm. 
The next step to improve and unify logging is to switch calls to ipt from open coding of output redirction to using cmd_wrapper(). This unfortunately also exposed some laxness in processing if iptables/ip6tables which we should also fix, IMHO...

Instead of using SQM_DEGUG to append all output into
a growing logfile, use three logfiles instead.
One for common code, mostly from run.sh, one for start-sqm and one for stop-sqm.
These logs are overwritten respectively on each invocation of either
run.sh, start-sqm or stop-sqm and will not grow indefintely and hence
can be enabled unconditionally so that this information is
available for debugging directly from "broken" sqm instances.

This commit also introduces ipt_new() in an attempt to convert
the legacy ipt() function to use cmd_wrapper to actually call
the iptables/ip6tables binaries. This exposes loads of errors
in ip[6]tables output and is hence not activated as default yet.

Signed-off-by: Sebastian Moeller <moeller0@gmx.de>

T

### CODE REVIEW

**Comment by moeller0** [comment]
Note we really should look into [https://github.com/tohojo/sqm-scripts/pull/58/commits/9c58c212fda6e303408be79024d5a059a5870d15](url) and [https://github.com/tohojo/sqm-scripts/pull/58/commits/8f79fb574907aa38935dfcffd3c778a391b37c11](url) to not try to handle non-existing chains/rules...

**Comment by tohojo** [comment]
Couple of comments:

- I can see the argument for clearing the log on every invocation, but why does it need three different files?

- Please lose the _new and _old stuff. We have git for tracking history, so instead of keeping the code around, structure commits so they are easy to revert. In this case, that would mean, keep the logging change only in a separate commit, then do all the iptables logging changes in a single commit (that just changes the ipt() function and adds the SILENT setting).


As for crediting Tony, you could do one of:

- using `git cherry-pick` to pick out the commit from his branch, fixing the merge conflicts and commiting with a note at the of the commit message detailing the changes you had to make to fix the merge. This should keep him as the commit author, but you as committer.

- Just credit him in the commit message (with a comment and/or a Suggested-By tag)...

**Comment by moeller0** [comment]
> On Aug 11, 2019, at 10:51, Toke Høiland-Jørgensen <notifications@github.com> wrote:
> 
> Couple of comments:
> 
> 	• I can see the argument for clearing the log on every invocation, but why does it need three different files?

	This simplifies lifetime issues, and elegantly solves the question when to overwrite the old log, always on invocation of run.sh, strt-sqm and stop-sqm. Also these logs are quite long, as they should, so separating them by start and stop should make them easier to digest, IMHO.

> 
> 	• Please lose the _new and _old stuff.

	Sure, I left this in just as a way to compare for this discussion (I know some folks prefer to look just at patches, but I prefer to look at the full files, so all relevant context is visible).

> We have git for tracking history, so instead of keeping the code around, structure commits so they are easy to revert.

	Again, solid advice, thanks. I first want to discuss the way the new solution can/should look before beautifying the PR.

> In this case, that would mean, keep the logging change only in a separate commit, then do all the iptables logging changes in a single commit (that just changes the ipt() function and adds the SILENT setting).

	+1.

> 
> As for crediting Tony, you could do one of:
> 
> 	• using git cherry-pick to pick out the commit from his branch,

	Will this work on a pull-request as well?

> fixing the merge conflicts and commiting with a note at the of the commit message detailing the changes you had to make to fix the merge. This should keep him as the commit author, but you as committer.
> 
> 	• Just credit him in the commit message (with a comment and/or a Suggested-By tag)...

	That sounds easier and less work, so I happily opt for this if this is considered good enough style.

Thanks

**Comment by tohojo** [comment]
moeller0 <notifications@github.com> writes:

>> On Aug 11, 2019, at 10:51, Toke Høiland-Jørgensen <notifications@github.com> wrote:
>> 
>> Couple of comments:
>> 
>> 	• I can see the argument for clearing the log on every invocation, but why does it need three different files?
>
> 	This simplifies lifetime issues, and elegantly solves the question when to overwrite the old log, always on invocation of run.sh, strt-sqm and stop-sqm. Also these logs are quite long, as they should, so separating them by start and stop should make them easier to digest, IMHO.

I would be worried that it's more difficult to get users to paste you
several files instead of just one long one?

You could just have run.sh clear the file before calling start - that
way you'd get a fresh file on every invocation, showing the history up
since the latest start; so including stop if one was issued, and not
otherwise...

>> 
>> 	• Please lose the _new and _old stuff.
>
> 	Sure, I left this in just as a way to compare for this discussion (I know some folks prefer to look just at patches, but I prefer to look at the full files, so all relevant context is visible).
>
>> We have git for tracking history, so instead of keeping the code around, structure commits so they are easy to revert.
>
> 	Again, solid advice, thanks. I first want to discuss the way the new solution can/should look before beautifying the PR.
>
>> In this case, that would mean, keep the logging change only in a separate commit, then do all the iptables logging changes in a single commit (that just changes the ipt() function and adds the SILENT setting).
>
> 	+1.
>
>> 
>> As for crediting Tony, you could do one of:
>> 
>> 	• using git cherry-pick to pick out the commit from his branch,
>
> 	Will this work on a pull-request as well?

Yeah, cherry-pick just applies the commit to whichever branch you are
currently on; so just do it on your pull request branch and that should
work.

>> fixing the merge conflicts and commiting with a note at the of the commit message detailing the changes you had to make to fix the merge. This should keep him as the commit author, but you as committer.
>> 
>> 	• Just credit him in the commit message (with a comment and/or a Suggested-By tag)...
>
> 	That sounds easier and less work, so I happily opt for this if
> 	this is considered good enough style.

Fine with me. As far as I'm concerned, the important thing is giving
credit; one can always discuss how prominent it should be, but the
commit message is fairly standard...

**Comment by moeller0** [comment]
> On Aug 11, 2019, at 12:04, Toke Høiland-Jørgensen <notifications@github.com> wrote:
> 
> moeller0 <notifications@github.com> writes:
> 
> >> On Aug 11, 2019, at 10:51, Toke Høiland-Jørgensen <notifications@github.com> wrote:
> >> 
> >> Couple of comments:
> >> 
> >> • I can see the argument for clearing the log on every invocation, but why does it need three different files?
> >
> > This simplifies lifetime issues, and elegantly solves the question when to overwrite the old log, always on invocation of run.sh, strt-sqm and stop-sqm. Also these logs are quite long, as they should, so separating them by start and stop should make them easier to digest, IMHO.
> 
> I would be worried that it's more difficult to get users to paste you
> several files instead of just one long one?

	Well, so far I got exactly zero logs send my way unsolicited, so I am confident that this is not going to be a big issue, and maybe I can whip up a short script that simply compresses and transfers /var/run/sqm for this purpose?

> 
> You could just have run.sh clear the file before calling start - that
> way you'd get a fresh file on every invocation, showing the history up
> since the latest start; so including stop if one was issued, and not
> otherwise...

        For a normal running SQM instance the invocation order is first stop then start, so with resetting on start I am almost guaranteed to not get the stop log from a running instance, no?
I admit that currently there is no logging in run.sh, so we could jettison that third log (my plan was to use that for logging of the locking changes that currently mature in one of the branches, but if we do not plan to pull these into master, we do not need the third log at all.)


> 
> >> 
> >> • Please lose the _new and _old stuff.
> >
> > Sure, I left this in just as a way to compare for this discussion (I know some folks prefer to look just at patches, but I prefer to look at the full files, so all relevant context is visible).
> >
> >> We have git for tracking history, so instead of keeping the code around, structure commits so they are easy to revert.
> >
> > Again, solid advice, thanks. I first want to discuss the way the new solution can/should look before beautifying the PR.
> >
> >> In this case, that would mean, keep the logging change only in a separate commit, then do all the iptables logging changes in a single commit (that just changes the ipt() function and adds the SILENT setting).
> >
> > +1.
> >
> >> 
> >> As for crediting Tony, you could do one of:
> >> 
> >> • using git cherry-pick to pick out the commit from his branch,
> >
> > Will this work on a pull-request as well?
> 
> Yeah, cherry-pick just applies the commit to whichever branch you are
> currently on; so just do it on your pull request branch and that should
> work.
> 

	Sorry, still confused, not so much about "my PR branch" but about the fact that Tony's committ only exist inside his PR from his forked repository, can I still cherry-pick from there without first importing his PR into a new branch?


> >> fixing the merge conflicts and commiting with a note at the of the commit message detailing the changes you had to make to fix the merge. This should keep him as the commit author, but you as committer.
> >> 
> >> • Just credit him in the commit message (with a comment and/or a Suggested-By tag)...
> >
> > That sounds easier and less work, so I happily opt for this if
> > this is considered good enough style.
> 
> Fine with me. As far as I'm concerned, the important thing is giving
> credit; one can always discuss how prominent it should be, but the
> commit message is fairly standard...

	Okay, will have a go at that.

**Comment by moeller0** [comment]
I guess, I will create a separate PR for switching ipt()/iptables/ip6tables over to using cmd_wrapper, as a) that seems like the right thing to do and b) should be uncontroversial. And then I will try a bit harder, how to get the logging improved.
I still thing that independent logs for start and stop seem an ecceptable trade-off versus the policy decision when to clear he existing log. A log that always contains the last invocations output seems simple enough to understand and reason about....

**Comment by tohojo** [comment]
moeller0 <notifications@github.com> writes:

>> On Aug 11, 2019, at 12:04, Toke Høiland-Jørgensen <notifications@github.com> wrote:
>> 
>> moeller0 <notifications@github.com> writes:
>> 
>> >> On Aug 11, 2019, at 10:51, Toke Høiland-Jørgensen <notifications@github.com> wrote:
>> >> 
>> >> Couple of comments:
>> >> 
>> >> • I can see the argument for clearing the log on every invocation, but why does it need three different files?
>> >
>> > This simplifies lifetime issues, and elegantly solves the question when to overwrite the old log, always on invocation of run.sh, strt-sqm and stop-sqm. Also these logs are quite long, as they should, so separating them by start and stop should make them easier to digest, IMHO.
>> 
>> I would be worried that it's more difficult to get users to paste you
>> several files instead of just one long one?
>
> 	Well, so far I got exactly zero logs send my way unsolicited, so I am confident that this is not going to be a big issue, and maybe I can whip up a short script that simply compresses and transfers /var/run/sqm for this purpose?

You're the one fielding the support questions, so whatever you think is
easier ;)

>> You could just have run.sh clear the file before calling start - that
>> way you'd get a fresh file on every invocation, showing the history up
>> since the latest start; so including stop if one was issued, and not
>> otherwise...
>
>         For a normal running SQM instance the invocation order is first stop then start, so with resetting on start I am almost guaranteed to not get the stop log from a running instance, no?
> I admit that currently there is no logging in run.sh, so we could jettison that third log (my plan was to use that for logging of the locking changes that currently mature in one of the branches, but if we do not plan to pull these into master, we do not need the third log at all.)

Hmm, yeah, I guess so...

>
>> 
>> >> 
>> >> • Please lose the _new and _old stuff.
>> >
>> > Sure, I left this in just as a way to compare for this discussion (I know some folks prefer to look just at patches, but I prefer to look at the full files, so all relevant context is visible).
>> >
>> >> We have git for tracking history, so instead of keeping the code around, structure commits so they are easy to revert.
>> >
>> > Again, solid advice, thanks. I first want to discuss the way the new solution can/should look before beautifying the PR.
>> >
>> >> In this case, that would mean, keep the logging change only in a separate commit, then do all the iptables logging changes in a single commit (that just changes the ipt() function and adds the SILENT setting).
>> >
>> > +1.
>> >
>> >> 
>> >> As for crediting Tony, you could do one of:
>> >> 
>> >> • using git cherry-pick to pick out the commit from his branch,
>> >
>> > Will this work on a pull-request as well?
>> 
>> Yeah, cherry-pick just applies the commit to whichever branch you are
>> currently on; so just do it on your pull request branch and that should
>> work.
>> 
>
> 	Sorry, still confused, not so much about "my PR branch" but about the fact that Tony's committ only exist inside his PR from his forked repository, can I still cherry-pick from there without first importing his PR into a new branch?

You can add his github fork as another remote to your local repository
and fetch from that; that gives you all the git objects so you can refer
to them (and even checkout the remote branches to look at the code
locally).

>
>> >> fixing the merge conflicts and commiting with a note at the of the commit message detailing the changes you had to make to fix the merge. This should keep him as the commit author, but you as committer.
>> >> 
>> >> • Just credit him in the commit message (with a comment and/or a Suggested-By tag)...
>> >
>> > That sounds easier and less work, so I happily opt for this if
>> > this is considered good enough style.
>> 
>> Fine with me. As far as I'm concerned, the important thing is giving
>> credit; one can always discuss how prominent it should be, but the
>> commit message is fairly standard...
>
> 	Okay, will have a go at that.

Cool.

**Comment by tohojo** [comment]
moeller0 <notifications@github.com> writes:

> I guess, I will create a separate PR for switching ipt()/iptables/ip6tables over to using cmd_wrapper, as a) that seems like the right thing to do and b) should be uncontroversial. And then I will try a bit harder, how to get the logging improved.
> I still thing that independent logs for start and stop seem an
> ecceptable trade-off versus the policy decision when to clear he
> existing log. A log that always contains the last invocations output
> seems simple enough to understand and reason about....

OK, I can live with that :)

**Comment by moeller0** [comment]
> Couple of comments:
> 
> * I can see the argument for clearing the log on every invocation, but why does it need three different files?
> * Please lose the _new and _old stuff. We have git for tracking history, so instead of keeping the code around, structure commits so they are easy to revert. In this case, that would mean, keep the logging change only in a separate commit, then do all the iptables logging changes in a single commit (that just changes the ipt() function and adds the SILENT setting).
> 
> As for crediting Tony, you could do one of:
> 
> * using `git cherry-pick` to pick out the commit from his branch, fixing the merge conflicts and commiting with a note at the of the commit message detailing the changes you had to make to fix the merge. This should keep him as the commit author, but you as committer.
> * Just credit him in the commit message (with a comment and/or a Suggested-By tag)...

Turns out that adding another remote and really using git to import commits for cherry-picking was much simpler than I feared. That way authorship tracking is conserved. Merging that old tree however was a bit of a challenge; but since I really do not want to import any grand redesign from there, that should not matter. The iptables tracking commits seem to work like a charm so all is good.

**Pull request closed without merging**
