### PR TITLE
iptables track and undo

### PR DESCRIPTION
**Pull request by moeller0**
This pulls in Tony's change to log our iptables actions on sqm-start and undo them on sqm-stop.
Passes my testing!

### CODE REVIEW

**Comment by tohojo** [comment]
Squashed the last two commits and fixed up the sed expression.

However, I didn't merge it because I'm a little concerned that we are basically executing the contents of the log. And we're not really doing much to ensure that the contents of that file is not tampered with.

We have the same issue for the variable state files, though, so not sure if it should hold up merging of this...

**Comment by moeller0** [comment]
> However, I didn't merge it because I'm a little concerned that we are basically executing the contents of the log. And we're not really doing much to ensure that the contents of that file is not tampered with.

Well, we also execute the contents of the .qos scripts without any checking (and actually I consider the ability of users to supply their own .qos -scripts to run inside the sqm machinery as one of the nicer points of having the whole thing coded in shell).
On OpenWrt there is no real escalation issue, as you need to be root to access either the shell or write data, so baring any remote file access bugs, "executing" the log, while ugly, does not seem to raise the level of insecurity materially, no?

> We have the same issue for the variable state files, though, so not sure if it should hold up merging of this...

Sure, one more script we just execute. Is /tmp/run/sqm in anyway more prone to attacks than /usr/lib/sqm, though?

**Comment by tohojo** [comment]
moeller0 <notifications@github.com> writes:

>> However, I didn't merge it because I'm a little concerned that we are basically executing the contents of the log. And we're not really doing much to ensure that the contents of that file is not tampered with.
>
> Well, we also execute the contents of the .qos scripts without any
> checking (and actually I consider the ability of users to supply their
> own .qos -scripts to run inside the sqm machinery as one of the nicer
> points of having the whole thing coded in shell).

Sure, but those are generally created once at install time with the
right permissions. Whereas we create and remove the state files
dynamically, which can lead to races.

> On OpenWrt there is no real escalation issue, as you need to be root
> to access either the shell or write data, so baring any remote file
> access bugs, "executing" the log, while ugly, does not seem to raise
> the level of insecurity materially, no?

Not on openwrt, no; but on other systems it could.

>> We have the same issue for the variable state files, though, so not
>> sure if it should hold up merging of this...
>
> Sure, one more script we just execute. Is /tmp/run/sqm in anyway more
> prone to attacks than /usr/lib/sqm, though?

Well, it depends. The problem is that we are creating them dynamically;
if someone manages to get permission to write into SQM_STATE_DIR, they
can get anything executed. For instance, if SQM_STATE_DIR is in /tmp and
doesn't exist, any user can create it...

I *think* things are a bit safer with /run/, though, so may not be such
an issue...

**Comment by moeller0** [comment]
> On Aug 15, 2019, at 19:09, Toke Høiland-Jørgensen <notifications@github.com> wrote:
> 
> moeller0 <notifications@github.com> writes:
> 
> >> However, I didn't merge it because I'm a little concerned that we are basically executing the contents of the log. And we're not really doing much to ensure that the contents of that file is not tampered with.
> >
> > Well, we also execute the contents of the .qos scripts without any
> > checking (and actually I consider the ability of users to supply their
> > own .qos -scripts to run inside the sqm machinery as one of the nicer
> > points of having the whole thing coded in shell).
> 
> Sure, but those are generally created once at install time with the
> right permissions. Whereas we create and remove the state files
> dynamically, which can lead to races.
> 
> > On OpenWrt there is no real escalation issue, as you need to be root
> > to access either the shell or write data, so baring any remote file
> > access bugs, "executing" the log, while ugly, does not seem to raise
> > the level of insecurity materially, no?
> 
> Not on openwrt, no; but on other systems it could.

	Ah, thanks forgot about that.

> 
> >> We have the same issue for the variable state files, though, so not
> >> sure if it should hold up merging of this...
> >
> > Sure, one more script we just execute. Is /tmp/run/sqm in anyway more
> > prone to attacks than /usr/lib/sqm, though?
> 
> Well, it depends. The problem is that we are creating them dynamically;
> if someone manages to get permission to write into SQM_STATE_DIR, they
> can get anything executed. For instance, if SQM_STATE_DIR is in /tmp and
> doesn't exist, any user can create it...

	But we will only source the state file as well as ipt_log when we change sqm's running status (so either if we start and or stop it) and then we also source defaults.sh and functions.sh (and omn start the selected qos-script). So again, I agree about the risk, but I still winder whether the attack surface gats much bigger? Could we try to use immutable flag and/or file permissions to make unexpected edits harder?

**Comment by tohojo** [comment]
moeller0 <notifications@github.com> writes:

>> On Aug 15, 2019, at 19:09, Toke Høiland-Jørgensen <notifications@github.com> wrote:
>> 
>> moeller0 <notifications@github.com> writes:
>> 
>> >> However, I didn't merge it because I'm a little concerned that we are basically executing the contents of the log. And we're not really doing much to ensure that the contents of that file is not tampered with.
>> >
>> > Well, we also execute the contents of the .qos scripts without any
>> > checking (and actually I consider the ability of users to supply their
>> > own .qos -scripts to run inside the sqm machinery as one of the nicer
>> > points of having the whole thing coded in shell).
>> 
>> Sure, but those are generally created once at install time with the
>> right permissions. Whereas we create and remove the state files
>> dynamically, which can lead to races.
>> 
>> > On OpenWrt there is no real escalation issue, as you need to be root
>> > to access either the shell or write data, so baring any remote file
>> > access bugs, "executing" the log, while ugly, does not seem to raise
>> > the level of insecurity materially, no?
>> 
>> Not on openwrt, no; but on other systems it could.
>
> 	Ah, thanks forgot about that.
>
>> 
>> >> We have the same issue for the variable state files, though, so not
>> >> sure if it should hold up merging of this...
>> >
>> > Sure, one more script we just execute. Is /tmp/run/sqm in anyway more
>> > prone to attacks than /usr/lib/sqm, though?
>> 
>> Well, it depends. The problem is that we are creating them dynamically;
>> if someone manages to get permission to write into SQM_STATE_DIR, they
>> can get anything executed. For instance, if SQM_STATE_DIR is in /tmp and
>> doesn't exist, any user can create it...
>
> 	But we will only source the state file as well as ipt_log when
> 	we change sqm's running status (so either if we start and or
> 	stop it) and then we also source defaults.sh and functions.sh
> 	(and omn start the selected qos-script).

All the code files are installed in /usr/lib which is generally expected
to contain executable code and is read-only.

/tmp is often a RAM disk, so it could very well be that empties out, at
which point anyone can create a new directory, owned by them, that
sqm-scripts will happily execute code as the next time it is run. And
presto, root code execution!

However, /run is expected to be non-writeable for users (according to
https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch03s15.html ) so I
think we're probably safe with that :)

**Comment by moeller0** [comment]
Ah, again thanks for the information. So I guess, this design seems okay-ish?

**Comment by tohojo** [comment]
Yeah, let's merge it...

**Pull request merged**
