### PR TITLE
Refactor + HFSC Based Script

### PR DESCRIPTION
**Pull request by zcecc22**
Dear Colleagues,

As discussed please find the changes for the new HFSC script.

Looking forward your feedback.

BR,
Vincent

### CODE REVIEW

**Comment by tohojo** [comment]
Looks good to me; @moeller0 any comments?

**Comment by moeller0** [comment]
Hi Time, Hi Vincent,

I am currently on the road, and away from (decent) internet connections and real computers, so I can not do anything meaningful right now. But if both of you are happy just merge it; we can always modify it later on ;). That said I should be back on Monday for a day and should find time to have a peek....



Best Regards
        Sebastian

On August 2, 2015 9:14:10 AM GMT+02:00, "Toke Høiland-Jørgensen" <notifications@github.com> wrote:
>Looks good to me; @moeller0 any comments?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/tohojo/sqm-scripts/pull/7#issuecomment-126995919

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by tohojo** [comment]
Went ahead and merged it. :)

**Comment by tohojo** [comment]
... before having read your latest comment; sorry. Guess you can change that in the HEAD now, though :)

**Comment by moeller0** [comment]
Hi Toke, 

Merging was fine. We can and will evolve with stuff inside the repository, and I think we have not exposed any of the changes in your new repository to the wider testing community, so there should be time to fix things up with minimal/no user perturbation ;)...

Best Regards
       Sebastian

On August 3, 2015 12:13:42 PM GMT+02:00, "Toke Høiland-Jørgensen" <notifications@github.com> wrote:
>... before having read your latest comment; sorry. Guess you can change
>that in the HEAD now, though :)
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/tohojo/sqm-scripts/pull/7#issuecomment-127184061

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by tohojo** [comment]
moeller0 <notifications@github.com> writes:

> Merging was fine. We can and will evolve with stuff inside the
> repository, and I think we have not exposed any of the changes in your
> new repository to the wider testing community, so there should be time
> to fix things up with minimal/no user perturbation ;)...

Sure. Putting up a new version based on this repo in the upstream
openwrt repo was next on my list, though; pending #6. Anything you want
to get in there before then? :)

-Toke

**Comment by moeller0** [comment]
Hi Toke,

On Aug 3, 2015, at 13:47 , Toke H�iland-J�rgensen <notifications@github.com> wrote:

> moeller0 <notifications@github.com> writes:
> 
> > Merging was fine. We can and will evolve with stuff inside the
> > repository, and I think we have not exposed any of the changes in your
> > new repository to the wider testing community, so there should be time
> > to fix things up with minimal/no user perturbation ;)...
> 
> Sure. Putting up a new version based on this repo in the upstream
> openwrt repo was next on my list, though; pending #6. Anything you want
> to get in there before then? :)

	I guess getting the link layer adjustments implemented in Vincent�s new script is the one thing I would like to have finished before pushing things into the openwrt repositories. Our claim was always we improve upon qos-scripts by the link layer handling and IPv6 (I have not yet checked Vincent�s new script for IPv6, I assume it is, but testing might still be a good idea), so it would be nice if we could keep this true. Other than that as no one is using Vincent�s script in our repository yet we can not introduce a regression so we should just include it as soon as I included the link layer handling.


Best Regards
	Sebastian

**Comment by tohojo** [comment]
moeller0 <notifications@github.com> writes:

> I guess getting the link layer adjustments implemented in Vincent�s
> new script is the one thing I would like to have finished before
> pushing things into the openwrt repositories. Our claim was always we
> improve upon qos-scripts by the link layer handling and IPv6 (I have
> not yet checked Vincent�s new script for IPv6, I assume it is, but
> testing might still be a good idea), so it would be nice if we could
> keep this true. Other than that as no one is using Vincent�s script in
> our repository yet we can not introduce a regression so we should just
> include it as soon as I included the link layer handling.

Okidoki, works for me. Let me know when you have fixed :)

-Toke

**Comment by moeller0** [comment]
Hi Toke,

On Aug 3, 2015, at 17:57 , Toke Høiland-Jørgensen <notifications@github.com> wrote:

> moeller0 <notifications@github.com> writes:
> 
> > I guess getting the link layer adjustments implemented in Vincent�s
> > new script is the one thing I would like to have finished before
> > pushing things into the openwrt repositories. Our claim was always we
> > improve upon qos-scripts by the link layer handling and IPv6 (I have
> > not yet checked Vincent�s new script for IPv6, I assume it is, but
> > testing might still be a good idea), so it would be nice if we could
> > keep this true. Other than that as no one is using Vincent�s script in
> > our repository yet we can not introduce a regression so we should just
> > include it as soon as I included the link layer handling.

	It turns out that Vincent implemented the link layer adjustments already, all I needed to do was looking at the checked in file on a screen bigger than my phone to notice ;) So by all means commit it to openwrt, and I will still run a few tests, but I assume all will just pass as Vincent did tests his erupts better than I did/do ;) Also IPv6 seems handled, so I expect all to work out well. The help text could be more verbose, but that is no merge-stopper in my book, I will try to expand this a bit after testing...

> 
> Okidoki, works for me. Let me know when you have fixed :)

	I consider this fixed, or better not in need of fixing, and blame my far-sightedness and my phones small screen for not noticing earlier.

Best Regards
	Sebastian

**Pull request merged**
