### PR TITLE
hfsc: due to kernel issues remove hfsc scripts for a stable LEDE 17.01

### PR DESCRIPTION
**Pull request by EricLuehrsen**
Delete: hfsc has issues with recent kernels and they are not all resolved. This commit burries hfsc scripts so that LEDE 17.01 users do not experience problems. This commit can be reverted at a newer kernel.

Surogate: Since we need to shelf hfsc for a while, this htb clone (simple_home.qos) may help residential users. (1) ISP may squash or change DSCP and (2) applications may not set these bits. This flavor uses protocol and port as inferences for DSCP.

Fix burst calculation step discontinuity.

Fix simple_tbf.qos misplaced DOWNLINK token.

### CODE REVIEW

**Comment by EricLuehrsen** [comment]
All tested on TP LINK WDR3600 and TP LINK ARCHER C7
@tohojo @moeller0

**Comment by dtaht** [comment]
I think offering too many choices for QoS is a bad idea and confusing people, secondly I tended to write off most reports of hfsc being better as confirmation bias, and thirdly... cake is stable enough (IMHO) to be the real default.

**Comment by EricLuehrsen** [comment]
I wouldnt say hfsc is "better," but it has nice features in the curve structure, and the algorythm theory would be great for a high utilization campus level gateway ... when it works.

Anyway for the sake of the poor user hfsc needs to be withdrawn from SQM. The kernel panics appear to be gone, but hfsc still goes internally unstable at load. Its a real mess.

**Comment by dtaht** [comment]
Just to try and clarify something: fq_codel provides all the features hfsc claims to have and more, when used with htb (or a device that has bql and/or hardware flow control). The fancy curve stuff in hfsc made some sense with sfq, but not in fq_codel, which has the "sparse packet optimization). Given how crashy hfsc has tended to be, I totally agree with burying it. Users keep selecting it, and it keeps not working (not just here but all over the net). 

However this pull request has non hfsc stuff in it, and I've not tested fiddling with ceil/etc for *years* in sqm's default configuration. Do you have data somewhere showing this change is better? (I can always be convinced with data. :) ) Similarly, I don't know if tbf is truly any "faster" or better than the htb stuff (or cake. TBF has one feature htb does not - it does gro peeling, as cake does.)

Were it up to me (and I don't regard myself as the maintainer of this stuff anymore), at least in the lede case, I'd make cake the default, and rip out pie, hfsc, tbf, and several other kernel modules that are not needed when cake is in use. 

Could you break this up into different requests?

**Comment by moeller0** [comment]
For a default it would be nice if it was at least in the process of being upstreamed into the kernel, no?

**Comment by EricLuehrsen** [comment]
Its all one request on purpose:
1 - remove hfsc ... then give back some side effect benefits hfsc had
2 - fix burst calculation for htb and tbf which is necessary on some lesser hardware, else htb/tbf throttle under rate due to cpu load. (hfsc/cake however bloat under load which undesirable).
3 - simple_tbf exists for some hardware, it has an error. (cake is not verified as dealing with the issue)
4 - replace hfsc_lite with simple_home where DSPC may not do any good, but port/protocol make fair inference (cake doesnt have this option).

**Comment by tohojo** [comment]
I tend to agree that adding another .qos script is not the right thing to do, at least not for the release. I consider the port-based prioritisation scheme somewhat dubious, and as far as I can see, that is the only difference between simple_home.qos and simple.qos?

As for defaulting to cake, that is really an issue for the packaging. I think from a user experience perspective, it would at least make sense to make sqm-scripts hard-depend on kmod-sched-cake, since otherwise layer_cake and piece_of_cake are just going to fail if someone tries them... But I'm not so sure about making it default.

**Comment by EricLuehrsen** [comment]
@tohojo Cherry pick as you will. I wanted to ensure this request removes hfsc, and end users have the opportunity for substantially simalar benefits.

Both my TL Archer C7 and WDR3600 significantly benifit from adjusting ceil> rate. That is just fundamental closed loop design.

My WDR3600 *needs* burst or HTB goes rock bottom, especially with all the WiFi devices at home.

The ports actually work when DSCP is not in play (squashed or just unused). Netflix, hulu, speed tests and general browing end up in class 11: DNS, VOIP signalling, DHCP, and VPN authentication end up in class 12: Bittorrent, VOIP data, WiFi Mobile Phone, and VPN data end up in 13: Class 12: is well protected. Class 11: packs up as full as it can. And fq_codel earns its keep in class 13:

I realize for the "enthusiast" this is not the academic ideal. But consider the muppet end user whose friend told him he can get a few more years of life from his older .11n device with LEDE 17.01.

**Comment by jgettys** [comment]
Only options we want end users to use should be in the base SQM module; everything else should be left to extras for experts to use.  

Cake is not in the base install, which seems like a mistake.

Present options in order we expect the most people to be likely to NEED them.  People don't read more than they think they should; this is why the first page of google for a search term is so valuable.

For example, the base sqm module presents codel, pie, and does not present cake in the qdisc options pull down.  Codel and Pie and the scripts they need for startup should be in extras.

If those unlikely to be used qdisc's are built in, they should become modules to save space.

If a script needs a particular qdisc, then it should be chosen automatically when a script is chosen, so that a naive user won't run a script to set up the wrong qdisc that won't be in force, generating needless problems and frustrations.

**Comment by tohojo** [comment]
I don't have anything against enabling bursting by default, but am not sure how the way you did it interacts with Luci. It may be better to change the default in /etc/config/sqm instead...

I'll look over the defaults, and the dependency resolution stuff, to see if we can get rid of some of the experimental qdiscs

**Comment by EricLuehrsen** [comment]
I will highly recommend you look at CEIL vs RATE. When they are equal, you can run any public speed test and see the head-bump saw tooth. If you have 75Mbps service, then you av erage 65-69. Move ceil +2% and you get smooth-ish closed loop control nearer 72-75.

When doing flent at home the drop packet or ECN response is so short, you likely dont see the pitch in the saw tooth. You would need 10 routers and ten 100m spools of patch cable to connect them to simulate.

**Comment by tohojo** [comment]
Okay, cherry-picked three of the commits... will hold off on the simple_home script until I know what will happen to https://patchwork.ozlabs.org/patch/717290/ (and thus how to handle dependencies and optional extras)

**Comment by EricLuehrsen** [comment]
I am okay to close this pull request then. I will rebase on this repo after its own update. I will generate a unique pull, then later.

**Comment by tohojo** [comment]
OK :)

As far as the ceil/rate settings, ceil seems to govern both the max burst rate, but also the borrowing from other classes. But it is possible to set burst without setting ceil, which would render the former meaningless? And there's also cburst. So it's not clear at all to me what the right thing to do is... :/

**Comment by EricLuehrsen** [comment]
@tohojo I get your trouble with HTB parameters. However if I consider analogs in automotive engine controls (carburator and distributor or full electronic), then it begins to make sense. Fuel mixture control does a lot of similar things. Rate, ceil, burst ... desired flow, injector flow max, and transient fuel puddle.

**Comment by moeller0** [comment]
> Only options we want end users to use should be in the base SQM module; everything else should be left to extras for experts to use.  

> Cake is not in the base install, which seems like a mistake.

Well, cake is not in the upstream linux kernel, nor IMHO in a robust process of getting ready for upstreaming; making a qdisc default that will not be available for most users seems a bit pre-mature...

> Present options in order we expect the most people to be likely to NEED them.  

That will basically just reflect our expectancies, no?

> People don't read more than they think they should; this is why the first page of google for a search term is so valuable.

> For example, the base sqm module presents codel, pie, and does not present cake in the qdisc options pull down. 

Assuming you have a reasonable recent sqm-scripts/luci-app-sqm installed as well as cake as a module you will finf cake in the drop down box, but if  there is no functional cake around it will not show in the drop down box. That seems relatively user friendly in my eyes?

> Codel and Pie and the scripts they need for startup should be in extras.

I disagree, the way sqm-scripts is structured is as a "frame-work" to allow easy and seemless switching between different qos scripts, that design looks pretty awkward and over engineered if all we offer is a single script.

> If those unlikely to be used qdisc's are built in, they should become modules to save space.

Is a module really smaller than the same functionality built in?

> If a script needs a particular qdisc, then it should be chosen automatically when a script is chosen, so that a naive user won't run a script to set up the wrong qdisc that won't be in force, generating needless problems and frustrations.

Not exactly sure what you are talking about here. We currently load a bunch of modules when running a qos script, that is not exactly taylored to that scripts need (including hfsc), but a) this is a clutch around openwrt's/lede's missing module autoload functionality. That said with hfsc using scripts gone we could remove sch_hfsc from the to-be-loaded-modules list...

**Comment by tohojo** [comment]
> Assuming you have a reasonable recent sqm-scripts/luci-app-sqm installed as well as cake as a module you will finf cake in the drop down box, but if there is no functional cake around it will not show in the drop down box. That seems relatively user friendly in my eyes?

Yes, except that all the `_cake.qos` scripts hard-code 'cake' as a qdisc and fail silently if it is not installed. I'm thinking we'll have to either have to do one of the following:

1. Have a way for a .qos script to declare that it should be hidden if a certain qdisc is not available (and apply that to *_cake.qos).
2. Move the cake scripts into a separate package (either sqm-scripts-extra or a new one), and have that one depend on kmod-sched-cake.
3. Simply have sqm-scripts unconditionally depend on kmod-sched-cake, thus ensuring that cake is always available.

I'm leaning towards 3. - thoughts?

**Comment by moeller0** [comment]
Well the description of piece_of_cake and layer_cake contain the following snippet:
"This script requires that cake is selected as qdisc."
I would respectfully say, if a user still selects this script but does not also select cake as qdisc, they are entitled to keep the pieces. I am very much opposed to hiding things. Let's not treat our users as idiots or assume they are unwilling to read?
I also believe we actually give an error message if cake is not useable (at least we have the following in the *_cake.qos scripts):
do_modules
    verify_qdisc $QDISC "cake" || return 1

which in theory should log something into the syslog. But maybe we should change the severity level in verify_qdisc from:
sqm_debug "QDISC $qdisc is ${not}useable."
to
sqm_error "QDISC $qdisc is ${not}useable." 
Maybe we need to show the errors also in the GUI somewhere?

I would lean for your 3, but unless cake gets further in upstreaming that might not be long-term viable. But as long as we are only talking about the openwrt/lede packages, where we have a "say" in whether cake is included 3 seems like the best short term option IMHO.
The existing sqm-scripts-extra package was intended as a quick way to distribute scripts under test that need more eyes and testers but are not far enough to be included in the main package, with *cake.qos scripts however in the way to replace simple.qos as the default, putting those into another package does not seem very obvious to me.

**Comment by tohojo** [comment]
On the one hand, I agree that we shouldn't underestimate our users. On the other, an interface that allows impossible combinations of options is a bad interface. I'll add kmod-sched-cake as a dependency when I update the package.

Thinking aloud about this some more, is there any conceptual differences between layer_cake.qos and simple.qos and between piece_of_cake.qos and simplest.qos? i.e. aren't the *cake variants simply reimplementations of the same basic concepts as the other two, but using cake? Because in that case, why are we asking the user to select the same thing twice (basically, whether or not to use cake), instead of just calling out to the cake variants if cake is selected as a qdisc?

**Comment by moeller0** [comment]
Erm, conceptually yes, but implementation wise each script has its own potential for bugs. So the user should know what they use instead of just configuring their intention, I believe. Also I am still thinking how to expose more of the more interesting cake options like nat and the dual-isolation options in the GUI, with that the cakes will be different enough from the simples to merit their own names. Plus it is valid to use cake as a leaf qdisc in the simple scripts right now, and for testing purposes I believe this is a good idea. But for openwrt/lede requiring cake will cut off back-ward compatibility with older pre-cake builds of openwrt (which might be acceptable, just something we should keep in mind).

**Pull request closed without merging**
